services:
  - type: web
    name: leaf-disease-classification
    env: python
    plan: free
    region: oregon
    rootDir: .
    buildCommand: pip install --no-cache-dir -r requirements.txt
    startCommand: python webapp/app.py
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PYTHON_VERSION
        value: "3.11.9"
