services:
  - type: web
    name: leaf-disease-classification
    env: python
    plan: free
    region: oregon
    rootDir: .
    buildCommand: pip install -U pip && pip install --no-cache-dir -r requirements.txt
    startCommand: gunicorn webapp.app:app --timeout 120 --workers 1 --threads 2
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PYTHON_VERSION
        value: "3.11.9"
